name: 'Jest Comments'
description: 'An action to comment on your Jest results '
inputs:
  who-to-greet:
    required: true
    default: 'My Little Mule: Peppy'
  test_cmd:  # id of input
    description: 'Test method to execute with npm/yarn'
    required: false
    default: 'node node_modules/jest/bin/jest'
  test_paths:  # id of input
    description: 'Array of test paths (e.g. client, server)'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'